mod_version=2.4.3
group=com.ethan.voxyworldgenv2
mod_name=Voxy World Gen V2
mod_author=iSeeEthan
mod_id=voxyworldgenv2

neo_minecraft_version=1.21.1
neo_minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.232
neo_version_range=[21.1.0,)
neo_loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neo_cloth_config_version=15.0.140

fabric_minecraft_version=26.2
fabric_api_version=0.153.0+26.2
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_cloth_config_version=26.2.155
mod_menu_version=20.0.0-beta.4

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
